"use strict";
exports.__esModule = true;
var books_1 = require("./books");
var libro1 = new books_1.book("nombre del viento", 250, "fkjgdf", "patrick rotfuss", "alfaguara");
libro1.getTitle();
libro1.getAuthor();
libro1.getEditorial();
libro1.getIsb();
libro1.getNpages();
libro1.setAuthor("Paloma");
libro1.setEditorial("Matrix");
libro1.setIsb("kjsdgkdf");
libro1.setNpages(4500);
libro1.setTitle("Tienes swing");
libro1.getTitle();
libro1.getAuthor();
libro1.getEditorial();
libro1.getIsb();
libro1.getNpages();
